### PR TITLE
#3 Added markdowns

### PR DESCRIPTION
**Pull request by micwin**
First bunch is the site.xml and the markdown files..

What still is is to do: 
- fill the changelog.md file, probably also use the changelog plugin or such  (I can do that)
- activate github pages (think this is done in the administrative concole of your github project)
- generate site and put it onto branch gh-pages

To make thinks more... comfortable for repository maintainer: 
- find a solution on how to automatically synchronize README.md and source/src/site/cookbook.md - or to put a link into README.md - or flatten out "source" directory into root directory of repository

### CODE REVIEW

**Comment by micwin** [comment]
Oh, sorry, missed to close it,...

**Comment by rugk** [comment]
> find a solution on how to automatically synchronize README.md and source/src/site/cookbook.md - or to put a link into README.md - or flatten out "source" directory into root directory of repository

Maybe use a symbolic link? (Don't know if this is supported by Git/GitHub, but maybe it is...)

> Oh, sorry, missed to close it,...

Why did you close this? Don't want to work on this any more?

**Comment by micwin** [comment]
To be honest, I really donnot know why I should contribute here any longer. I donnot see that you are willing to improve the Threema API here significantly. This pull request stands ready to be merged since around 5 months. There is no feedback, no review, no progress at all. Same with the maven central deployment - do you even plan to do that? I have no feedback on that. No reaction, not even a private note or such. I am working as a freelancer build engineer right now. You could hire me for thrusting your maven builds, sit back, watch the show, but as long as I am contributing for free, I expect a little bit more action on your side. Which is not happening. So well, no, I dont want to work on that for free any more., Landsmann hin Landsmann her.

**Comment by threema-ch** [comment]
Thanks for your input. Maven central deployment is not currently planned.

**Pull request closed without merging**
